### ISSUE TITLE
Need a newer version of pims

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/auto-build-tagged-recipes#7]
@danielballan what version of pims can you do `from pims import pipeline`?

**Comment by ericdill** [comment]
I'm getting an error on the csxtools build

**Comment by ericdill** [comment]
```
===== testing package: csxtools-0.1.2-np110py34_0 =====
import: 'csxtools'
/opt/conda/envs/_test/lib/python3.4/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/opt/conda/envs/_test/lib/python3.4/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/opt/conda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import csxtools
  File "/opt/conda/envs/_test/lib/python3.4/site-packages/csxtools/__init__.py", line 8, in <module>
    from .utils import get_fastccd_images
  File "/opt/conda/envs/_test/lib/python3.4/site-packages/csxtools/utils.py", line 4, in <module>
    from pims import pipeline
ImportError: cannot import name 'pipeline'
TESTS FAILED: csxtools-0.1.2-np110py34_0
```

**Comment by ericdill** [comment]
no rush, im done for the evening and will check again tomorrow, thanks!

**Comment by danielballan** [comment]
Latest tag 0.3.3 should work.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Fri, Feb 19, 2016 at 4:24 PM -0800, "Eric Dill" <notifications@github.com<mailto:notifications@github.com>> wrote:


===== testing package: csxtools-0.1.2-np110py34_0 ===== import: 'csxtools' /opt/conda/envs/_test/lib/python3.4/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
 warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.') /opt/conda/envs/_test/lib/python3.4/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take
 a moment. warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.') Traceback (most recent call last): File "/opt/conda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module> import csxtools File "/opt/conda/envs/_test/lib/python3.4/site-packages/csxtools/__init__.py",
 line 8, in <module> from .utils import get_fastccd_images File "/opt/conda/envs/_test/lib/python3.4/site-packages/csxtools/utils.py", line 4, in <module> from pims import pipeline ImportError: cannot import name 'pipeline' TESTS FAILED: csxtools-0.1.2-np110py34_0

**Comment by ericdill** [comment]
Thanks @danielballan . I have added the pims 0.3.3 recipe to this repo and added pims >=0.3.3 in csxtools. cc @stuwilkins
